overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@<=1.13.4: '>=1.13.5'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  cookie@<0.7.0: '>=0.7.0'
  engine.io@>=5.1.0 <6.4.2: '>=6.4.2'
  got@<11.8.5: '>=11.8.5'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  multer@<2.0.1: '>=2.0.1'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  sanitize-html@<2.0.0-beta: '>=2.0.0-beta'
  sanitize-html@<2.12.1: '>=2.12.1'
  sanitize-html@<2.3.1: '>=2.3.1'
  sanitize-html@<2.3.2: '>=2.3.2'
  sanitize-html@<2.7.1: '>=2.7.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  sharp@<0.32.6: '>=0.32.6'
  socket.io@>=3.0.0 <4.6.2: '>=4.6.2'
  tmp@<=0.2.3: '>=0.2.4'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
