overrides:
  brace-expansion@<5.0.5: '>=5.0.5'
  cookie@<0.7.0: '>=0.7.0'
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  immutable@<3.8.3: '>=3.8.3'
  picomatch@<2.3.2: '>=2.3.2'
  picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  tmp@<=0.2.3: '>=0.2.4'
  webpack@>=5.49.0 <5.104.0: '>=5.104.0'
  webpack@>=5.49.0 <=5.104.0: '>=5.104.1'
  yaml@>=1.0.0 <1.10.3: '>=1.10.3'
  yaml@>=2.0.0 <2.8.3: '>=2.8.3'
