overrides:
  axios@<0.30.0: '>=0.30.0'
  axios@<0.30.2: '>=0.30.2'
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  cookie@<0.7.0: '>=0.7.0'
  engine.io@>=5.1.0 <6.4.2: '>=6.4.2'
  got@<11.8.5: '>=11.8.5'
  postcss@<8.4.31: '>=8.4.31'
  sanitize-html@<2.0.0-beta: '>=2.0.0-beta'
  sanitize-html@<2.12.1: '>=2.12.1'
  sanitize-html@<2.3.1: '>=2.3.1'
  sanitize-html@<2.3.2: '>=2.3.2'
  sanitize-html@<2.7.1: '>=2.7.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  sharp@<0.32.6: '>=0.32.6'
  socket.io@>=3.0.0 <4.6.2: '>=4.6.2'
  tmp@<=0.2.3: '>=0.2.4'
  webpack-dev-middleware@<=5.3.3: '>=5.3.4'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
