minimumReleaseAgeExclude:
  - cookie@0.7.0
  - tmp@0.2.4
  - webpack@5.104.1
  - webpack@5.104.0
  - serialize-javascript@7.0.3
  - file-type@21.3.1
  - path-to-regexp@0.1.13
  - lodash@4.17.24
  - '@parcel/reporter-dev-server@2.16.4'
  - immutable@3.8.3
  - ws@8.20.1
  - serialize-javascript@7.0.5
  - uuid@11.1.1
  - qs@6.15.2
  - tmp@0.2.6
